apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: famer-
nameSuffix: -c
namespace: farmer-c1




resources:
- ../../base

patchesStrategicMerge:
        - deployment.yml
        - pvc.yml
