apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-farmer-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 52Gi
  storageClassName: rook-ceph-block 
