apiVersion: apps/v1
kind: Deployment
metadata:
  name: famer-test-deployment
  labels:
    app: famer-test
spec:
  replicas: 1
  strategy:
     type: Recreate
  selector:
    matchLabels:
      app: famer-test
  template:
    metadata:
      labels:
        app: famer-test

    spec:
      securityContext:
          runAsUser: 0


      containers:
      - name: famer-test
        image: ghcr.io/subspace/farmer:gemini-2a-2022-sep-10 
        ports:
          - containerPort: 30533
        env:
        - name: ADDRESS
          valueFrom:
            configMapKeyRef:
              key: ADDRESS
              name: envconfig
        - name: PLOT-SIZE
           valueFrom:
            configMapKeyRef:
              key: PLOT-SIZE
              name: envconfig

        command: [
      "/subspace-farmer",
      "farm",
      "--node-rpc-url", "ws://hongkong.subspace.blocknode.run:9944",
      "--listen-on", "/ip4/0.0.0.0/tcp/30533",
      "--reward-address", $(ADDRESS),
      # Replace `PLOT_SIZE` with plot size in gigabytes or terabytes, for example 100G or 2T (but leave at least 60G of disk space for node and some for OS)
      "path=/var/subspace,size=$(PLOT-SIZE)",

    ]

        volumeMounts:
          - name: farmer-data
            mountPath: "/var/subspace"
      volumes:
        - name: farmer-data
          persistentVolumeClaim:
                  claimName: pvc-farmer-test

