apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: farmer-test-1
images:
      - name:  ghcr.io/subspace/farmer
        newName: ghcr.io/subspace/farmer
        newTag:  gemini-3f-2023-sep-05

resources:
  - namespace.yml
  - deployment.yml
  - pvc.yml
